# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _

# return code
SUCCESS = 0
UNKNOWN_ERROR = 1
BAD_REQUEST = 2
NO_PERMISSION = 3
AUTHENTICATION_FAILED = 4
NOT_AUTHENTICATED = 5
NOT_SUPPORT = 6
DATABASE_ERROR = 7
DATA_CONFLICT = 8
DELETE_FORBIDDEN = 9
LOGIN_FAILED = 10
LICENSE_EXPIRING = 11
LICENSE_LIMIT = 12
NO_SCHOOL = 13
NOT_FOUND = 14
UPDATE_FORBIDDEN = 15
WEATHER_GET_FAILED = 0x101
WEATHER_NOT_AREA_INFO = 0x102
STUDENT_DOES_NOT_EXISTS = 0x201
SIGN_DEVICE_DOES_NOT_EXISTS = 0x202
CLASSROOM_DOES_NOT_EXISTS = 0x204
COURSE_ATTENDANCE_TABLE_DOES_NOT_EXISTS = 0x205
FILE_TOO_LARGE = 0x206
CLASS_DOES_NOT_EXISTS = 0x207
MENU_TOO_MANY = 0x208
MYSQL_GONE_AWAY = 0x210

FILE_NOT_FOUND = 301
UPGRADE_FILE_INVALID = 302
UPGRADE_FILE_NOT_FOUND = 304
FACE_SERVER_ERROR = 306
NOT_IN_ATTENDANCE = 307
FACE_SERVER_DISABLE = 308
FACE_GROUP_NOT_FOUND = 309
CREATE_FACE_GROUP_FAILED = 400
DELETE_FACE_GROUP_FAILED = 401
CREATE_FACE_CODE_FAILED = 305
DELETE_FACE_CODE_FAILED = 402
CHECK_FACE_FAILED = 403

MISS_PARAMETER = 501
CAMERA_NOT_BIND_OR_EXIST = 502
CURRENT_NOT_ATTENDANCE_TIME = 503
PARAMETER_ERROR = 504
STUDENT_COURSE_CONFLICT = 505
CONTROL_CAMERA_ERROR = 506
QUESTION_GET_FAILED = 507

WAREHOUSE_GET_FAILED = 601
# return message
RETURN_MSG = {
    SUCCESS: _('正常。'),
    UNKNOWN_ERROR: _('未知错误。'),
    BAD_REQUEST: _('错误请求格式。'),
    NO_PERMISSION: _('无访问权限。'),
    AUTHENTICATION_FAILED: _('用户名或密码错误。'),
    NOT_AUTHENTICATED: _('请登录。'),
    NOT_SUPPORT: _('不支持。'),
    LICENSE_EXPIRING: _('授权已过期或未授权，请联系管理员。'),
    LICENSE_LIMIT: _('超过授权账户最大允许的用户数，请联系管理员。'),
    NOT_FOUND: _("未查询到"),
    WEATHER_GET_FAILED: _('天气获取失败'),
    WEATHER_NOT_AREA_INFO: _('没有设置学校位置信息'),
    STUDENT_DOES_NOT_EXISTS: _('学生不存在'),
    SIGN_DEVICE_DOES_NOT_EXISTS: _('签到设备不存在'),
    CLASSROOM_DOES_NOT_EXISTS: _('教室不存在'),
    CLASS_DOES_NOT_EXISTS: _('班级不存在'),
    COURSE_ATTENDANCE_TABLE_DOES_NOT_EXISTS: _('课程考勤不存在'),
    FILE_TOO_LARGE: _('上传文件太大'),
    FILE_NOT_FOUND: _('无法找到文件'),
    UPGRADE_FILE_INVALID: _('升级文件无效'),
    UPGRADE_FILE_NOT_FOUND: _('无法找到升级文件'),
    DATABASE_ERROR: _('数据库错误'),
    DATA_CONFLICT: _('数据冲突'),
    DELETE_FORBIDDEN: _('禁止删除'),
    LOGIN_FAILED: _('登录失败'),
    MENU_TOO_MANY: _('定制菜单超过数量'),
    MYSQL_GONE_AWAY: _('数据库连接失败'),
    NO_SCHOOL: _('未传递学校信息'),
    CREATE_FACE_CODE_FAILED: _('上传的图片不能正常识别人脸'),
    FACE_SERVER_ERROR: _('人脸服务器设置或网络异常'),
    NOT_IN_ATTENDANCE: _('不在考勤时间'),
    FACE_GROUP_NOT_FOUND: _('学校的人脸识别组未检查到'),
    CREATE_FACE_GROUP_FAILED: _('创建学校人脸识别组失败'),
    DELETE_FACE_GROUP_FAILED: _('删除学校人脸识别组失败'),
    DELETE_FACE_CODE_FAILED: _('删除人脸识别码失败'),
    CHECK_FACE_FAILED: _('未查询到该图片对应的人'),
    MISS_PARAMETER: _("缺少重要参数"),
    CAMERA_NOT_BIND_OR_EXIST: _("摄像头未绑定教室或不存在"),
    CURRENT_NOT_ATTENDANCE_TIME: _("当前时段不在考勤范围"),
    PARAMETER_ERROR: _("参数错误"),
    STUDENT_COURSE_CONFLICT: _("学生课程冲突"),
    UPDATE_FORBIDDEN: _("禁止修改"),
    CONTROL_CAMERA_ERROR: _("控制摄像头出错"),
    QUESTION_GET_FAILED: _("问卷题目获取失败"),
    WAREHOUSE_GET_FAILED: _("线上素材库获取失败")
}
