# Generated by Django 3.0.4 on 2021-03-30 10:01

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import pandora.models.account.user
import pandora.utils.snowflake


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.BigIntegerField(default=pandora.utils.snowflake.SnowIdWorkerPool.get_id, help_text='唯一标识uid', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间, 2018-1-1T1:1:1.1111')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间, 2018-1-1T1:1:1.1111')),
                ('name', models.CharField(blank=True, help_text='姓名', max_length=128, null=True)),
                ('description', models.TextField(blank=True, help_text='备注', null=True)),
                ('avatar', models.CharField(blank=True, help_text='头像', max_length=512, null=True)),
                ('gender', models.CharField(choices=[('NA', '未知'), ('M', '男'), ('F', '女')], default='M', help_text='性别', max_length=2)),
                ('birthday', models.DateField(blank=True, help_text='生日', null=True)),
                ('email', models.EmailField(blank=True, help_text='邮箱', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='电话', max_length=64, null=True)),
                ('role', models.CharField(choices=[('superadmin', '超级管理员'), ('admin', '管理员'), ('general', '普通用戶'), ('guest', '访客'), ('developer', '开发者')], default='general', help_text='角色', max_length=32)),
                ('username', models.CharField(error_messages={'unique': '用户名已经存在.'}, help_text='必填. 字符,数字和符号@/./+/-/_ ,最大长度150 ', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', pandora.models.account.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CatalogPermissionGroup',
            fields=[
                ('uid', models.BigIntegerField(default=pandora.utils.snowflake.SnowIdWorkerPool.get_id, help_text='唯一标识uid', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间, 2018-1-1T1:1:1.1111')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间, 2018-1-1T1:1:1.1111')),
                ('client_id', models.CharField(help_text='项目标签', max_length=100)),
                ('name', models.CharField(help_text='组中文名称', max_length=255)),
                ('code', models.CharField(blank=True, help_text='操作权限编码', max_length=64, null=True)),
                ('description', models.CharField(blank=True, help_text='简介', max_length=255, null=True)),
                ('category', models.SmallIntegerField(default=1, help_text='组权限类型, 1:自建数据,2:外部数据,3:系统数据')),
                ('status', models.IntegerField(default=0, help_text='0:禁用,1:启用')),
                ('level', models.SmallIntegerField(default=4, help_text='组权限数据级别')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('uid', models.BigIntegerField(default=pandora.utils.snowflake.SnowIdWorkerPool.get_id, help_text='唯一标识uid', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间, 2018-1-1T1:1:1.1111')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间, 2018-1-1T1:1:1.1111')),
                ('name', models.CharField(db_index=True, help_text='名称', max_length=64)),
                ('code', models.CharField(db_index=True, help_text='标识码', max_length=32)),
                ('description', models.TextField(blank=True, help_text='简介', null=True)),
                ('extra_info', models.TextField(blank=True, help_text='可扩展属性', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('uid', models.BigIntegerField(default=pandora.utils.snowflake.SnowIdWorkerPool.get_id, help_text='唯一标识uid', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间, 2018-1-1T1:1:1.1111')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间, 2018-1-1T1:1:1.1111')),
                ('client_id', models.CharField(help_text='项目标签', max_length=100)),
                ('alias', models.CharField(help_text='模块英文名称', max_length=64)),
                ('name', models.CharField(db_index=True, help_text='名称', max_length=32)),
                ('code', models.CharField(db_index=True, help_text='编码', max_length=32)),
                ('terminals', models.IntegerField(default=0, help_text='1:手机,2:平板,4:笔记本, PC')),
                ('description', models.TextField(blank=True, help_text='简介', null=True)),
                ('category', models.CharField(default='menu', max_length=20)),
                ('status', models.IntegerField(default=1, help_text='0:禁用,1:启用')),
                ('mode', models.IntegerField(default=7, help_text='4:读,2:写,1:授权')),
                ('sort_number', models.IntegerField(blank=True, help_text='显示排序值', null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(db_constraint=False, help_text='父节点', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pandora.Menu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('uid', models.BigIntegerField(default=pandora.utils.snowflake.SnowIdWorkerPool.get_id, help_text='唯一标识uid', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间, 2018-1-1T1:1:1.1111')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间, 2018-1-1T1:1:1.1111')),
                ('key', models.CharField(db_index=True, max_length=40, verbose_name='Key')),
                ('browser', models.CharField(blank=True, max_length=20, null=True)),
                ('os', models.CharField(blank=True, max_length=20, null=True)),
                ('platform', models.CharField(blank=True, max_length=20, null=True)),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('uid', models.BigIntegerField(default=pandora.utils.snowflake.SnowIdWorkerPool.get_id, help_text='唯一标识uid', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间, 2018-1-1T1:1:1.1111')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间, 2018-1-1T1:1:1.1111')),
                ('client_id', models.CharField(help_text='项目标签', max_length=100)),
                ('alias', models.CharField(help_text='模块英文名称', max_length=64)),
                ('code', models.CharField(help_text='模块编码', max_length=64)),
                ('name', models.CharField(help_text='模块中文名称', max_length=255)),
                ('terminals', models.IntegerField(default=0, help_text='1:手机,2:平板,4:笔记本, PC')),
                ('category', models.CharField(default='module', max_length=20)),
                ('status', models.IntegerField(default=1, help_text='0:禁用,1:启用')),
                ('mode', models.IntegerField(default=7, help_text='4:读,2:写,1:授权')),
                ('description', models.TextField(blank=True, help_text='简介', null=True)),
                ('sort_number', models.IntegerField(blank=True, help_text='显示排序值', null=True)),
                ('menu', models.ForeignKey(db_constraint=False, help_text='菜单', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module', to='pandora.Menu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogPermissionGroupModule',
            fields=[
                ('uid', models.BigIntegerField(default=pandora.utils.snowflake.SnowIdWorkerPool.get_id, help_text='唯一标识uid', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间, 2018-1-1T1:1:1.1111')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间, 2018-1-1T1:1:1.1111')),
                ('mode', models.IntegerField(default=0, help_text='4:读,2:写,1:授权')),
                ('company', models.ForeignKey(db_constraint=False, help_text='公司', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pandora.Company')),
                ('group', models.ForeignKey(db_constraint=False, help_text='组, uid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_module', to='pandora.CatalogPermissionGroup')),
                ('module', models.ForeignKey(db_constraint=False, help_text='模块', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_group', to='pandora.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogPermissionGroupMenu',
            fields=[
                ('uid', models.BigIntegerField(default=pandora.utils.snowflake.SnowIdWorkerPool.get_id, help_text='唯一标识uid', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间, 2018-1-1T1:1:1.1111')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间, 2018-1-1T1:1:1.1111')),
                ('mode', models.IntegerField(default=0, help_text='4:读,2:写,1:授权')),
                ('company', models.ForeignKey(db_constraint=False, help_text='公司', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pandora.Company')),
                ('group', models.ForeignKey(db_constraint=False, help_text='组, uid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_menu', to='pandora.CatalogPermissionGroup')),
                ('menu', models.ForeignKey(db_constraint=False, help_text='菜单', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_group', to='pandora.Menu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogPermissionGroupMember',
            fields=[
                ('uid', models.BigIntegerField(default=pandora.utils.snowflake.SnowIdWorkerPool.get_id, help_text='唯一标识uid', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间, 2018-1-1T1:1:1.1111')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间, 2018-1-1T1:1:1.1111')),
                ('company', models.ForeignKey(db_constraint=False, help_text='公司', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pandora.Company')),
                ('group', models.ForeignKey(db_constraint=False, help_text='组, uid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_member_user', to='pandora.CatalogPermissionGroup')),
                ('user', models.ForeignKey(db_constraint=False, help_text='用户, uid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_member_group', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='catalogpermissiongroup',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='公司', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pandora.Company'),
        ),
    ]
